# Generated by Django 5.0 on 2024-01-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.IntegerField(null=True),
        ),
    ]
