# Generated by Django 5.0 on 2024-01-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
